const fields = [
  "Air pollution",
  "Water quality",
  "Soil contamination",
  "Climate change",
  "Occupational health",
  "Radiation exposure",
  "Toxicology",
  "Epidemiology",
  "Environmental policy",
  "Pesticides",
  "Hazardous waste",
  "Food safety",
  "Indoor air quality",
  "Chemical exposure",
  "Waste management",
  "Environmental justice",
  "Public health",
  "Global health",
  "Sustainable development",
  "Noise pollution",
  "Waterborne diseases",
  "Vector-borne diseases",
  "Biomonitoring",
  "Environmental health risk assessment",
  "Green spaces",
  "Built environment",
  "Urban planning",
  "Climate resilience",
  "Energy policy",
  "Chemical safety",
  "Environmental exposure",
  "Health effects of climate change",
  "Emerging contaminants",
  "Environmental degradation",
  "Health impact assessments",
  "Bioaccumulation",
  "Eco-toxicology",
  "Human exposure pathways",
  "Climate-induced migration",
  "Wastewater treatment",
  "Public health emergencies",
  "Pharmaceutical contaminants",
  "Natural disasters and health",
  "Environmental epidemiology",
  "Environmental exposure biomarkers",
  "Foodborne illnesses",
  "Risk communication",
  "Sustainable agriculture",
  "Climate adaptation strategies",
  "Environmental health disparities",
  "Energy efficiency",
  "Sustainable cities",
  "Marine pollution",
  "Air quality monitoring",
  "Water purification technologies",
  "Recycling and waste reduction",
  "Health effects of air pollutants",
  "Soil health and agriculture",
  "Exposure assessment methods",
  "Impact of deforestation",
  "Environmental health education",
  "Climate and health policy",
  "Agricultural runoff",
  "Health and environmental economics",
  "Land use and health",
  "Chemical spill response",
  "Microbial contamination",
  "Climate change and vector ecology",
  "Environmental risk modeling",
  "Contaminant source tracking",
  "Sustainable transportation",
  "Indoor environmental quality",
  "Green building practices",
  "Health impacts of industrial activities",
  "Water scarcity and health",
  "Environmental health monitoring",
  "Environmental regulations",
  "Health effects of noise pollution",
  "Ecosystem services and health",
  "Chemical risk management",
  "Health impact of environmental policies",
  "Climate change and health inequities",
  "Landfill management",
  "Water resource management",
  "Public health interventions",
  "Environmental health and justice",
  "Health effects of heavy metals",
  "Green chemistry",
  "Air quality standards",
  "Environmental health promotion",
  "Climate change mitigation strategies",
  "Environmental health research methods",
];

export default fields;
