version: '3.8'

services:
  daatelli-frontend:
    build:
      context: ../src/frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - daatelli-backend

  daatelli-backend:
    build:
      context: ../src/backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
