apiVersion: apps/v1
kind: Deployment
metadata:
  name: daatelli-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: daatelli-frontend
  template:
    metadata:
      labels:
        app: daatelli-frontend
    spec:
      containers:
        - name: daatelli-frontend
          image: 980798/daatelli-frontend:0.1.0
---
apiVersion: v1
kind: Service
metadata:
  name: daatelli-frontend-service
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 80
  selector:
    app: daatelli-frontend
