name: Docker Build and Push

on:
  push:
    branches:
      - stable
  pull_request:
    branches:
      - stable

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASS }}

      - name: Build and push Frontend image
        uses: docker/build-push-action@v2
        with:
          context: ./src/frontend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/frontend:0.1.0

      - name: Build and push Backend image
        uses: docker/build-push-action@v2
        with:
          context: ./src/backend
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/backend:0.1.0

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
